[package]
name = "core"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
bitfields = "1.0.0"

